# Generated by Django 4.2.6 on 2023-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comix_shops',
            name='year',
            field=models.DateTimeField(null=True, verbose_name='Укажите дату выпуска манги'),
        ),
    ]
